# Generated by Django 5.2.7 on 2025-10-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(help_text='URL of the original article', unique=True)),
                ('title', models.CharField(help_text='Article title', max_length=500)),
                ('content', models.TextField(help_text='Full article content')),
                ('summary', models.TextField(blank=True, help_text='AI-generated summary in Ukrainian', null=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('uk', 'Ukrainian'), ('ru', 'Russian')], default='en', help_text='Language of the article', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Processing status', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, help_text='Original publication date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When article was added to our system')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update time')),
                ('word_count', models.PositiveIntegerField(default=0, help_text='Number of words in content')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['language'], name='news_articl_languag_ce3527_idx'), models.Index(fields=['status'], name='news_articl_status_a95c4c_idx'), models.Index(fields=['created_at'], name='news_articl_created_4ed0e6_idx'), models.Index(fields=['published_at'], name='news_articl_publish_90ca8c_idx')],
            },
        ),
    ]
