# Generated by Django 5.2.7 on 2025-10-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='authors',
            field=models.CharField(blank=True, help_text='Article authors', max_length=300),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Meta description from source', max_length=500),
        ),
        migrations.AddField(
            model_name='article',
            name='source_domain',
            field=models.CharField(blank=True, help_text='Domain of the source website', max_length=100),
        ),
        migrations.AddField(
            model_name='article',
            name='top_image',
            field=models.URLField(blank=True, help_text='URL of the main article image'),
        ),
        migrations.AlterField(
            model_name='article',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('uk', 'Ukrainian'), ('ru', 'Russian'), ('de', 'German'), ('fr', 'French'), ('es', 'Spanish'), ('it', 'Italian'), ('unknown', 'Unknown')], default='unknown', help_text='Language of the article', max_length=10),
        ),
    ]
